### PR TITLE
add new designed background

### PR DESCRIPTION
**Pull request by violoncelloCH**
here is my new designed background :) (including the source .svg)
if you wish any changes (colours?), I'm happy to add them to this PR :)
once this PR is merged I'll create follow-up PRs to the android and desktop repos, if that's what you want

cc @r10s 

https://support.delta.chat/t/new-chat-background/226

new background       |  current background
:-------------------------:|:-------------------------:
img_20190218_071034  |  img_20190218_071007

### CODE REVIEW

**Comment by hpk42** [comment]
i don't think using characters and symbols for background in a chat view is a good idea -- chatting is often confusing enough.  Or am i misunderstanding something?  
Also, i admit i kind of like the current background ;)

**Comment by violoncelloCH** [comment]
@hpk42 I get what you mean, but that's just a matter of contrast honestly... If you keep the contrast low it's neither distracting nor confusing, I think. (I added a comparison and a link to the forum for reference to my original post^)
Also if you take a look at what e.g. Threema or Whatsapp are doing, that seems to work too:

threema         |  whatsapp
:-------------------------:|:-------------------------:
 |

**Comment by karissa** [comment]
nice work, thanks for looking at this, i do think your background is a bit less intrusive

**Comment by dbrown428** [comment]
You've done a lovely job designing this background pattern, it's much quieter than the previous one, but is it possible to not have a background at all? I come from chat apps that don't have background images, and so my first thought when I installed DeltaChat was "how do I get rid of this background"

**Comment by angelo-fuchs** [comment]
I personally would love to have several different backgrounds to choose from and this is definitely one of the elements that should be available.

**Comment by adbenitez** [comment]
I also agree with @angelo-fuchs about having more than one default background to choose from.

**Comment by Hocuri** [comment]
Well... What is this waiting for?

**Comment by r10s** [comment]
i am wondering if using a svg file for a background has some, maybe bad impacts. not sure, however, iirc even for icons it could cause problems.

apart from that, design questions are hard :)

**Comment by Hocuri** [comment]
> i am wondering if using a svg file for a background has some, maybe bad impacts. not sure, however, iirc even for icons it could cause problems.

I didn't get the point... converting this to a jpg shouldn't be a problem, I think

> apart from that, design questions are hard :)

Actually, AFAIK everyone who commented preferred the new background over the old one :+1: Or did I miss something?

**Comment by r10s** [comment]
> I didn't get the point... converting this to a jpg shouldn't be a problem, I think

sure, however, someone has to pick this up.
and this just has not happened for $reasons :)

**Comment by karissa** [comment]
keeping it the same format as the old one usually is a good idea in my experience, and png is pretty fast.

**Comment by Hocuri** [comment]
Actually, the pull request does contain a jpg so you just have to remove the svg if you do not want it:

https://github.com/deltachat/interface/blob/59b46a30a6e825a728f068a2c52d38e2750a2daa/background/background_hd.jpg

**Comment by r10s** [comment]
> Actually, the pull request does contain a jpg so you just have to remove the svg if you do not want it:

you're right, i've overseen that. so, everything is right from that point of view :)

**Comment by r10s** [comment]
merging, this is the interface registry (to be honest, i've overseen this in the last ;)
so, it think, it would be nice to have some additional backgrounds here.

it would be really cool if we can offer some nice backgrounds alternatives to the user sooner or later, so this might be a first step.

**Comment by violoncelloCH** [comment]
thank you for merging!
would be nice if there were multiple backgrounds for the user to choose from... sadly I don't have that much coding experience yet and no experience with Android coding at all to implement this...

**Pull request merged**
