### PR TITLE
mention that "Invite Links" use a OPENPGP4FPR variant

### PR DESCRIPTION
**Pull request by r10s**
closes https://github.com/deltachat/invite/issues/19

### CODE REVIEW

**Review by adbenitez — APPROVED** [review]

**Comment by Simon-Laux** [comment]
do you really think that is enough and matches the level of detail that the file already sets? I'm very disappointed.

**Comment by r10s** [comment]
> do you really think that is enough and matches the level of detail that the file already sets? I'm very disappointed.

i assume, you have not noted that the linked repo contains a new README explaining invite-links and differences to OPENPGP4FPR. also note, that there was just _nothing_ before :)

**Comment by Simon-Laux** [comment]
> i assume, you have not noticed that the linked repo contains a new README explaining invite-links and differences to OPENPGP4FPR

Indeed I have missed that, I also wasn't expecting it there. I'll copy the wording where possible so the review will be easier.

**Comment by Simon-Laux** [comment]
The readme of https://github.com/deltachat/invite/ is actually really nice, but it is more targeted at users and does not describe how the format exactly works (escaping of the `#` char after the fingerprint) and does not mention platform support as you already mentioned in your comment above.

**Pull request merged**
