### PR TITLE
add docs about known ui config keys

### PR DESCRIPTION
**Pull request by Simon-Laux**

### CODE REVIEW

**Comment by lk108** [comment]
Would it be acceptable to add DeltaTouch to the `usage` column?

In `uri-schemes.md`, there are two lines per scheme:
* `Available on`, which I assume is only for official clients, and
* `Other apps using it`, probably the line for inofficial clients such as DeltaTouch. Or is this line intended for non-DC related apps?

**Comment by r10s** [comment]
> Would it be acceptable to add DeltaTouch to the usage column?

not sure what the gist of the document is in detail, however, if it is eg. about making sure that adding new config values do not collide with existing ones, i'd say adding DeltaTouch makes sense, as well as bots (only for the "known larger ones" a grep would do as well and the effort of maintaining an extra document seems less needed).

so: yes, i'd say it makes sense to add add DeltaTouch to the usage column :)

**Comment by Simon-Laux** [comment]
yeah it's basically about sharing knowledge about used uri schemes, we can discuss the structure/design of it, I just started writing it down, the structure is not final yet though. so extra column or adding delta touch to the available on column are both fine with me.

**Comment by Simon-Laux** [comment]
also for uri schemes: I would put delta touch in "available on", the "other apps using it" is for things outside of the deltachat universe.
If you want we can have a distinction via sth like "deltatouch (community, ubuntu touch)" or sth like that.

**Comment by Simon-Laux** [comment]
For bots I would say only for bot frameworks or other cases where an account is "shared" between multiple bots or the ui key appears in multiple bots, but as this document is called known_ui_config, it could also include everything that is known.

**Pull request merged**
